# Generated by Django 3.2 on 2022-02-16 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_usuario', models.CharField(max_length=200)),
                ('telefono_usuario', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Cover',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen1_carousel', models.ImageField(upload_to='cover_imagenes')),
                ('imagen2_carousel', models.ImageField(upload_to='cover_imagenes')),
                ('imagen3_carousel', models.ImageField(upload_to='cover_imagenes')),
                ('imagen4_carousel', models.ImageField(upload_to='cover_imagenes')),
                ('facebook', models.CharField(blank=True, max_length=250, null=True)),
                ('instagram', models.CharField(blank=True, max_length=250, null=True)),
                ('whatsapp', models.CharField(blank=True, max_length=250, null=True)),
                ('ubicacion', models.CharField(blank=True, max_length=250, null=True)),
                ('citas_cover', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CuentaCobro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cliente_soporte', models.CharField(max_length=200)),
                ('empresa_responsable', models.CharField(max_length=200)),
                ('cuenta_cobro_imagen', models.ImageField(upload_to='cuenta_iimagenes')),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('actividad', models.CharField(max_length=300)),
                ('direccion', models.CharField(max_length=200)),
                ('numero', models.CharField(max_length=13)),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('nombre', models.CharField(max_length=200)),
                ('valor', models.DecimalField(decimal_places=3, max_digits=13)),
                ('copia_digital', models.FileField(upload_to='eventos_archivos')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('categoria', models.CharField(max_length=30)),
                ('descripcion', models.CharField(max_length=550)),
                ('imagen1', models.ImageField(upload_to='productos_imagenes')),
                ('imagen2', models.ImageField(upload_to='productos_imagenes')),
                ('imagen3', models.ImageField(upload_to='productos_imagenes')),
                ('imagen4', models.ImageField(upload_to='productos_imagenes')),
                ('precio', models.DecimalField(decimal_places=0, max_digits=30)),
            ],
        ),
        migrations.CreateModel(
            name='QuienesSomos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen_corporativa', models.ImageField(upload_to='cover_imagenes')),
                ('titulo_principal', models.CharField(max_length=40)),
                ('descripcion_principal', models.CharField(max_length=200)),
                ('titulo_secundario', models.CharField(max_length=40)),
                ('descripcion_secundario', models.CharField(max_length=200)),
            ],
        ),
    ]
