# Generated by Django 4.1 on 2022-09-27 01:01

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='categorias_imagenes')),
            ],
        ),
        migrations.CreateModel(
            name='CategoriaBarra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ProductoBarra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_barras', models.CharField(default='0', max_length=20)),
                ('nombre', models.CharField(max_length=200)),
                ('costo_estructural', models.DecimalField(decimal_places=2, max_digits=10)),
                ('costo_unitario', models.DecimalField(decimal_places=2, max_digits=8)),
                ('precio_venta', models.DecimalField(decimal_places=2, max_digits=8)),
                ('stock', models.SmallIntegerField()),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sitio.categoriabarra')),
            ],
        ),
        migrations.DeleteModel(
            name='Empresa',
        ),
        migrations.DeleteModel(
            name='Evento',
        ),
        migrations.RenameField(
            model_name='contacto',
            old_name='telefono_usuario',
            new_name='identificacion_personal',
        ),
        migrations.RemoveField(
            model_name='cover',
            name='citas_cover',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='imagen3',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='imagen4',
        ),
        migrations.AddField(
            model_name='contacto',
            name='efectuado',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contacto',
            name='producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sitio.producto'),
        ),
        migrations.AddField(
            model_name='contacto',
            name='qr_descargado',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contacto',
            name='qr_enviado',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contacto',
            name='telefono',
            field=models.CharField(default='XXX', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cover',
            name='audio',
            field=models.FileField(default='XXX', upload_to='cover_audio'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='fecha',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 9, 26, 20, 0, 28, 473447), null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='telefono',
            field=models.CharField(blank=True, default='0', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='cover',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='descripcion',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='producto',
            name='nombre',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='quienessomos',
            name='descripcion_principal',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='quienessomos',
            name='descripcion_secundario',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='quienessomos',
            name='titulo_principal',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='quienessomos',
            name='titulo_secundario',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sitio.categoria'),
        ),
    ]
