# Generated by Django 4.1 on 2022-09-27 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0002_categoria_categoriabarra_productobarra_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='fecha',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
