# Generated by Django 4.1 on 2022-10-03 19:21

from django.db import migrations, models
from datetime import datetime


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0003_alter_producto_fecha'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('medio_pago', models.CharField(max_length=20)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('costo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('costo_estructural', models.DecimalField(decimal_places=2, max_digits=10)),
                ('beneficio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('margen_ganancia', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.DeleteModel(
            name='CuentaCobro',
        ),
        migrations.AddField(
            model_name='contacto',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True, default=datetime.now()),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cover',
            name='facebook',
            field=models.URLField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='cover',
            name='instagram',
            field=models.URLField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='cover',
            name='ubicacion',
            field=models.URLField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=11),
        ),
        migrations.AlterField(
            model_name='productobarra',
            name='codigo_barras',
            field=models.CharField(default='0', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='productobarra',
            name='costo_estructural',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='productobarra',
            name='precio_venta',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
