# Generated by Django 4.1 on 2022-10-03 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0004_transaccion_delete_cuentacobro_contacto_fecha_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransaccionProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_transaccion', models.CharField(max_length=20)),
                ('codigo', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=200)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=11)),
            ],
        ),
        migrations.AlterField(
            model_name='productobarra',
            name='costo_estructural',
            field=models.DecimalField(decimal_places=2, max_digits=11),
        ),
        migrations.AlterField(
            model_name='productobarra',
            name='costo_unitario',
            field=models.DecimalField(decimal_places=2, max_digits=11),
        ),
        migrations.AlterField(
            model_name='productobarra',
            name='precio_venta',
            field=models.DecimalField(decimal_places=2, max_digits=11),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='beneficio',
            field=models.DecimalField(decimal_places=2, max_digits=11),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='costo',
            field=models.DecimalField(decimal_places=2, max_digits=11),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='costo_estructural',
            field=models.DecimalField(decimal_places=2, max_digits=11),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='margen_ganancia',
            field=models.DecimalField(decimal_places=2, max_digits=11),
        ),
    ]
