# Generated by Django 4.1 on 2022-10-25 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0006_remove_transaccionproducto_codigo_transaccion_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaccionproducto',
            old_name='precio',
            new_name='costo',
        ),
        migrations.RemoveField(
            model_name='transaccionproducto',
            name='codigo',
        ),
        migrations.AddField(
            model_name='transaccion',
            name='estado_transaccion',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaccionproducto',
            name='costo_estructural',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=11),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaccionproducto',
            name='precio_venta',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=11),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cover',
            name='facebook',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='cover',
            name='instagram',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='cover',
            name='ubicacion',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='beneficio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='costo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='costo_estructural',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='margen_ganancia',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True),
        ),
    ]
