# Generated by Django 4.1 on 2022-10-27 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0007_rename_precio_transaccionproducto_costo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaccion',
            old_name='estado_transaccion',
            new_name='estado',
        ),
    ]
