# Generated by Django 4.1 on 2022-10-27 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0008_rename_estado_transaccion_transaccion_estado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaccionproducto',
            old_name='costo',
            new_name='costo_unitario',
        ),
    ]
