# Generated by Django 4.1 on 2022-11-07 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0009_rename_costo_transaccionproducto_costo_unitario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaccion',
            name='margen_ganancia',
        ),
    ]
