# Generated by Django 4.1 on 2022-11-07 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0010_remove_transaccion_margen_ganancia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaccion',
            name='beneficio',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=11),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='costo',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=11),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='costo_estructural',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=11),
        ),
    ]
