# Generated by Django 4.1 on 2022-11-08 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0012_rename_efectuado_contacto_estado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaccion',
            name='ocultada',
        ),
    ]
