# Generated by Django 4.1 on 2022-11-13 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0013_remove_transaccion_ocultada'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacto',
            name='qr_pdf',
            field=models.FileField(blank=True, null=True, upload_to='qr_pdf_entradas'),
        ),
        migrations.AddField(
            model_name='transaccion',
            name='tipo',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
