# Generated by Django 4.1 on 2022-11-13 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0016_alter_transaccion_beneficio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaccion',
            name='tipo',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
