# Generated by Django 4.1 on 2022-11-16 00:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0017_alter_transaccion_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransaccionReporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('estado', models.BooleanField(blank=True, null=True)),
                ('nota', models.TextField()),
                ('transaccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sitio.transaccion')),
            ],
        ),
    ]
