# Generated by Django 4.1 on 2022-11-17 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0018_transaccionreporte'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contacto',
            name='qr_pdf',
        ),
        migrations.AddField(
            model_name='contacto',
            name='codigo_qr',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='contacto',
            name='fichero_qr',
            field=models.FileField(blank=True, null=True, upload_to='ficheros_qr'),
        ),
    ]
