# Generated by Django 4.1 on 2022-11-20 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0019_remove_contacto_qr_pdf_contacto_codigo_qr_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='fichero_qr',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
