# Generated by Django 4.1 on 2022-12-02 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0020_alter_contacto_fichero_qr'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contacto',
            old_name='codigo_qr',
            new_name='codigo',
        ),
        migrations.RenameField(
            model_name='contacto',
            old_name='fichero_qr',
            new_name='fichero',
        ),
        migrations.RenameField(
            model_name='contacto',
            old_name='qr_descargado',
            new_name='fichero_descargado',
        ),
        migrations.RenameField(
            model_name='contacto',
            old_name='qr_enviado',
            new_name='fichero_enviado',
        ),
    ]
