# Generated by Django 4.1 on 2022-12-09 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0021_rename_codigo_qr_contacto_codigo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='codigo',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='beneficio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
