# Generated by Django 4.1 on 2022-12-10 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0022_alter_contacto_codigo_alter_transaccion_beneficio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productobarra',
            name='costo_estructural',
        ),
    ]
