# Generated by Django 4.1 on 2022-12-12 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0023_remove_productobarra_costo_estructural'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cover',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='cover_audio'),
        ),
        migrations.AlterField(
            model_name='cover',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
