# Generated by Django 4.1 on 2022-12-16 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0025_contacto_link_fichero'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contacto',
            name='link_fichero',
        ),
        migrations.AlterField(
            model_name='contacto',
            name='fichero',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
