# Generated by Django 4.1 on 2022-12-16 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0026_remove_contacto_link_fichero_alter_contacto_fichero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='fichero',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
