# Generated by Django 4.1 on 2022-12-16 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0027_alter_contacto_fichero'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacto',
            name='codigo_descarga',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='contacto',
            name='link_descarga',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='fichero',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
