# Generated by Django 4.1 on 2022-12-17 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0028_contacto_codigo_descarga_contacto_link_descarga_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='codigo_descarga',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='fichero',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
