# Generated by Django 4.1 on 2022-12-17 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0029_alter_contacto_codigo_descarga_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='fichero',
            field=models.FileField(blank=True, null=True, upload_to='ficheros'),
        ),
    ]
