# Generated by Django 4.1 on 2022-12-17 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0030_alter_contacto_fichero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='fichero',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
