# Generated by Django 4.0.2 on 2023-07-14 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0031_alter_contacto_fichero'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaccion',
            name='descuento',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=11),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='fichero',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='beneficio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='costo',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=11),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='costo_estructural',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=11),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=11),
        ),
    ]
