# Generated by Django 4.0.2 on 2023-07-20 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0033_remove_cover_audio_remove_cover_imagen2_carousel_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='archivopdf',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='telefono',
        ),
        migrations.AddField(
            model_name='cover',
            name='empresa',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cover',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='cover_imagenes'),
        ),
        migrations.AddField(
            model_name='producto',
            name='imagen3',
            field=models.ImageField(blank=True, null=True, upload_to='productos_imagenes'),
        ),
        migrations.AddField(
            model_name='producto',
            name='imagen4',
            field=models.ImageField(blank=True, null=True, upload_to='productos_imagenes'),
        ),
        migrations.AddField(
            model_name='producto',
            name='imagen5',
            field=models.ImageField(blank=True, null=True, upload_to='productos_imagenes'),
        ),
        migrations.AddField(
            model_name='producto',
            name='imagen6',
            field=models.ImageField(blank=True, null=True, upload_to='productos_imagenes'),
        ),
        migrations.AddField(
            model_name='producto',
            name='precio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True),
        ),
    ]
