# Generated by Django 4.0.2 on 2023-07-31 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0034_remove_producto_archivopdf_remove_producto_telefono_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='precio',
            new_name='precio_informativo',
        ),
        migrations.AddField(
            model_name='producto',
            name='precio_pagos',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True),
        ),
    ]
