# Generated by Django 4.2.4 on 2023-08-04 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0035_rename_precio_producto_precio_informativo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productobarra',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='contacto',
            name='codigo',
        ),
        migrations.RemoveField(
            model_name='contacto',
            name='codigo_descarga',
        ),
        migrations.RemoveField(
            model_name='contacto',
            name='fichero',
        ),
        migrations.RemoveField(
            model_name='contacto',
            name='fichero_descargado',
        ),
        migrations.RemoveField(
            model_name='contacto',
            name='fichero_enviado',
        ),
        migrations.RemoveField(
            model_name='contacto',
            name='link_descarga',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='precio_pagos',
        ),
        migrations.RemoveField(
            model_name='transaccion',
            name='tipo',
        ),
        migrations.AddField(
            model_name='contacto',
            name='enviado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='producto',
            name='precio_pago',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio_informativo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
        migrations.DeleteModel(
            name='CategoriaBarra',
        ),
        migrations.DeleteModel(
            name='ProductoBarra',
        ),
    ]
