# Generated by Django 4.2.4 on 2023-08-07 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0036_remove_productobarra_categoria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='estado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cover',
            name='correo',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
    ]
