# Generated by Django 4.2.4 on 2023-08-07 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0037_alter_contacto_estado_alter_cover_correo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contacto',
            name='estado',
        ),
    ]
