# Generated by Django 4.0.2 on 2023-09-06 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0038_remove_contacto_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cover',
            name='correo',
        ),
        migrations.RemoveField(
            model_name='cover',
            name='frase',
        ),
        migrations.RemoveField(
            model_name='cover',
            name='imagen1_carousel',
        ),
        migrations.RemoveField(
            model_name='cover',
            name='twitter',
        ),
    ]
