# Generated by Django 4.2.4 on 2023-09-25 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0039_remove_cover_correo_remove_cover_frase_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='ubicacion_producto',
        ),
        migrations.AddField(
            model_name='producto',
            name='acomodacion',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='aforo',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='categoria_evento',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='comida',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='edad',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='embarazadas',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='imagen_evento1',
            field=models.ImageField(default=None, upload_to='productos_imagenes'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='imagen_evento2',
            field=models.ImageField(default=None, upload_to='productos_imagenes'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='licor',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='lugar',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='movilidad_reducida',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='notas',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='puertas',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='ubicacion',
            field=models.URLField(blank=True, null=True),
        ),
    ]
