# Generated by Django 4.0.2 on 2023-12-04 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0040_remove_producto_ubicacion_producto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cover',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='media/cover_imagenes'),
        ),
        migrations.AlterField(
            model_name='quienessomos',
            name='imagen_corporativa',
            field=models.ImageField(upload_to='media/cover_imagenes'),
        ),
    ]
