# Generated by Django 4.0.2 on 2023-12-28 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0042_alter_cover_logo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cover',
            name='logo_footer',
            field=models.ImageField(blank=True, null=True, upload_to='cover_imagenes'),
        ),
    ]
