# Generated by Django 4.0.2 on 2023-12-28 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0043_cover_logo_footer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='imagen_evento1',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='imagen_evento2',
        ),
    ]
