# Generated by Django 4.0.2 on 2023-12-29 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0044_remove_producto_imagen_evento1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='precio_informativo',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='precio_pago',
        ),
        migrations.AddField(
            model_name='producto',
            name='precio_general',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
    ]
