# Generated by Django 4.0.2 on 2023-12-29 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0046_producto_nombre_referencia1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='hora',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
