# Generated by Django 4.0.2 on 2023-12-29 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0047_producto_hora'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='etiquetas',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='fondo',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
