# Generated by Django 4.0.2 on 2023-12-29 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0048_producto_etiquetas_producto_fondo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='ubicacion',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
