# Generated by Django 4.0.2 on 2023-12-30 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0049_alter_producto_ubicacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cover',
            name='facebook',
        ),
        migrations.RemoveField(
            model_name='cover',
            name='instagram',
        ),
    ]
