# Generated by Django 4.0.2 on 2023-12-30 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0050_remove_cover_facebook_remove_cover_instagram'),
    ]

    operations = [
        migrations.AddField(
            model_name='cover',
            name='enlace_patrocinador1',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='cover',
            name='enlace_patrocinador2',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='cover',
            name='enlace_patrocinador3',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='cover',
            name='enlace_patrocinador4',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='cover',
            name='enlace_patrocinador5',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='cover',
            name='logo_patrocinador1',
            field=models.ImageField(blank=True, null=True, upload_to='cover_imagenes'),
        ),
        migrations.AddField(
            model_name='cover',
            name='logo_patrocinador2',
            field=models.ImageField(blank=True, null=True, upload_to='cover_imagenes'),
        ),
        migrations.AddField(
            model_name='cover',
            name='logo_patrocinador3',
            field=models.ImageField(blank=True, null=True, upload_to='cover_imagenes'),
        ),
        migrations.AddField(
            model_name='cover',
            name='logo_patrocinador4',
            field=models.ImageField(blank=True, null=True, upload_to='cover_imagenes'),
        ),
        migrations.AddField(
            model_name='cover',
            name='logo_patrocinador5',
            field=models.ImageField(blank=True, null=True, upload_to='cover_imagenes'),
        ),
    ]
