# Generated by Django 4.0.2 on 2023-12-30 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0051_cover_enlace_patrocinador1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='acomodacion',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='aforo',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='categoria_evento',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='comida',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='edad',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='embarazadas',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='hora',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='imagen5',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='imagen6',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='licor',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='lugar',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='movilidad_reducida',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='notas',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='precio_general',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='puertas',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='stock',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='ubicacion',
        ),
        migrations.AlterField(
            model_name='producto',
            name='imagen1',
            field=models.ImageField(blank=True, null=True, upload_to='productos_imagenes'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='imagen2',
            field=models.ImageField(blank=True, null=True, upload_to='productos_imagenes'),
        ),
    ]
