# Generated by Django 4.0.2 on 2023-12-30 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0052_remove_producto_acomodacion_remove_producto_aforo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='fecha',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
