# Generated by Django 4.0.2 on 2024-01-01 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0053_producto_fecha'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='nombre_referencia1',
            new_name='head_colum1',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='nombre_referencia2',
            new_name='head_colum2',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='nombre_referencia3',
            new_name='head_colum3',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='nombre_referencia4',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='nombre_referencia5',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='precio_referencia1',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='precio_referencia2',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='precio_referencia3',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='precio_referencia4',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='precio_referencia5',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='stock_referencia1',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='stock_referencia2',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='stock_referencia3',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='stock_referencia4',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='stock_referencia5',
        ),
    ]
