# Generated by Django 4.0.2 on 2024-01-01 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0054_rename_nombre_referencia1_producto_head_colum1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='colum1_row1',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='colum2_row1',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='colum3_row1',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
