# Generated by Django 4.0.2 on 2024-02-13 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0056_producto_colum1_row10_producto_colum1_row2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_documento', models.CharField(blank=True, max_length=200, null=True)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='documentos')),
            ],
        ),
    ]
