# Generated by Django 4.0.2 on 2024-02-14 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0057_lista'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='etiquetas',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='fondo',
        ),
    ]
