# Generated by Django 4.0.2 on 2024-02-14 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0058_remove_producto_etiquetas_remove_producto_fondo'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='problemas',
            field=models.FileField(blank=True, null=True, upload_to='problemas'),
        ),
        migrations.AddField(
            model_name='producto',
            name='tomo',
            field=models.FileField(blank=True, null=True, upload_to='tomos'),
        ),
        migrations.AddField(
            model_name='producto',
            name='video',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
